FROM caddy:builder AS builder

# Build Caddy with pinned versions of TencentCloud and Cloudflare DNS modules
RUN caddy-builder github.com/caddy-dns/tencentcloud@v0.4.1 github.com/caddy-dns/cloudflare@v0.2.1

FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy

#docker buildx build  -t caddy-dns:latest .